### ISSUE TITLE
Help: Encoders don't fit through the top plate

### ISSUE THREAD

**Issue by InvisibleFunction** [josefadamcik/SofleKeyboard#118]
**Kind of issue?**
Bug / Assembly / HELP!_

**Which Board?**
Original

**Which Board Revision?**
2.0

**What steps have you taken**
* [x] I have searched the Issues page
* [x] I have read the documentation 

**What is the issue?**
My encoders don't fit through the top plate. It appears the hole is exactly the size of the encoders. I've tried some aliexpress encoders and some real Alps encoders. Are there some that are known to fit?

My reading suggested that filing the hole could release nasty stuff that I don't want to breathe.

**Comment by InvisibleFunction** [comment]
I talked to the person who ordered the boards that I have and he said that they might have been "dev" boards, but I am not familiar enough with the project history to really know what that means. The top plates do say "v2.0" without any indication of them being a release candidate or beta or anything. If it would be helpful to further identify the boards I have please let me know, otherwise I will just file these down.

Thanks!

**Comment by josefadamcik** [comment]
@InvisibleFunction 
I did check the design and your dimensions. Based on all the information it does look you ended up with the WIP version that had the holes ridiculously small. I don't say there can't be problems with the current design, it's always hard to say since the final process and tolerances are always gonna be specific to the manufacturer. But I decided I am not gonna change the design at the moment.

Thaks for all the information!
