### ISSUE TITLE
removing the top line

### ISSUE THREAD

**Issue by beraldoleal** [josefadamcik/SofleKeyboard#16]
Hi @josefadamcik, first of all, this is super cool. Thanks for this board. Greate design.

One question: how difficult would be to remove the first line (numbers) and maybe bringing down a little the promicro, oled and trrs jack? I'm very used to 40% and your design is perfect for me, except that addional line. :/

**Comment by josefadamcik** [comment]
@beraldoleal 

It would require some effort and some knowledge of PCB design and KiCad. I do have such skills and from this point of view the change would be not difficult. 

Deleting the rows and routing for them is actually pretty easy. Moving around the controller would require some rerouting but  it's also not a big deal. From my experience, the trickiest and most annoying part is actually changing the shape of the PCB and making the top and bottom plates. KiCad doesn't provide good support for this (since keyboard are not really a usual PCB shape) so I use Inkscape and  some tricks how to ransfer data between KiCad and Inkscape in both directions in order to make sure things (like holes for keys and screws) are properly aligned.  I had to find some strategies how to solve those problems but they are not particularly good and efficient and maybe it's possible to find a better way. But just figuring out how to do it, if you don't have the experience, requires quite some effort.

Based on how you asked the question, I assume that you don't really know your way around PCB design etc. If that's the case, you need to decide if you want to learn it and if you don't mind investing the time (which will be more than actually making the modifications to the board). I am interested in DIY electronics in general, so for me it was an opportunity to learn more how things are done. Sofle is actually a modification of Lilly58 Pro so I had to learn all the things mentioned above to make it. I didn't have to learn all the things I would need to design a keyboard from scratch. Today, I would be able to do that for sure. I wrote about my [experience on my blog](https://josef-adamcik.cz/electronics/let-me-introduce-you-sofle-keyboard-split-keyboard-based-on-lily58.html ). There are even some tips mentioned, but  it's not a tutorial. 

Hope the answer helps. Good luck on your DIY keyboard path.
