### ISSUE TITLE
Pro micro don't work when is connected to the PCB

### ISSUE THREAD

**Issue by danieltoro** [josefadamcik/SofleKeyboard#83]
Kind of issue? Assembly 

Which Board? RGB

Which Board Revision?  RGB = 2.1

What is the issue? Pro micro won't work when I conected to the pcb, either i can't flash with the pcb reset button

![IMG_1219](https://user-images.githubusercontent.com/12534317/119601721-c2374900-bdb7-11eb-9069-87e129b01d54.jpg)
![IMG_1220](https://user-images.githubusercontent.com/12534317/119601731-ca8f8400-bdb7-11eb-81df-2967e7729674.jpg)

I don't know what to do

**Comment by DaneEvans** [comment]
Do the LEDs stay lit?
If yes, it's a reset issue.
If no, it's a power issue.

Is the pro micro on the correct set of headers for the side of the board?

On the right half, micro on top of board, USB down = right set of headers

On the left half, micro on top, and USB down = right set of headers.

I'd need to look at the schematics to work out other configs.

**Comment by danieltoro** [comment]
this is the pcb for my left hand 

![IMG_1221](https://user-images.githubusercontent.com/12534317/119602820-0297c680-bdba-11eb-9b65-2bede03252ee.jpg)

**Comment by DaneEvans** [comment]
Assuming you are putting the micro on with the components towards this PCB,
it's right.

Is the micro losing power (no lights showing)?

Did you test it before putting the LEDs on? If they are around the wrong
way it can cause the micro to lose power. That's probably the most likely
from what I've seen before.

**Comment by Liilnopitynope** [comment]
I am having the same issue where pro micro alone is working but once I plugged it in the PCB it's not working. The LED indicator on the pro micro itself is lighting up, but my pc is not recognizing the board, but none of the other LEDs on the board is working.

**Comment by danieltoro** [comment]
> I am having the same issue where pro micro alone is working but once I plugged it in the PCB it's not working. The LED indicator on the pro micro itself is lighting up, but my pc is not recognizing the board, but none of the other LEDs on the board is working.

**Comment by danieltoro** [comment]
@Liilnopitynope can do you make it work?

**Comment by DLopezGo90** [comment]
My right half is working but left isn't 

Right half (working):

![image](https://user-images.githubusercontent.com/59780264/120550974-873ea200-c3c3-11eb-8f43-0508cd44bb53.png)

Left half (not working, Pro Micro doesn't turn on and gets hot):

![image](https://user-images.githubusercontent.com/59780264/120551485-13e96000-c3c4-11eb-8cb9-e9eca10eb07e.png)

Should I put the Pro Micro with the components facing upward (not toward the PCB) on the left half?

![image](https://user-images.githubusercontent.com/59780264/120552022-b4d81b00-c3c4-11eb-88b9-2ad832bf75e3.png)

Help please

**Comment by DaneEvans** [comment]
It's getting hot because you have a short.  

2 options I can see, wrong header, or an LED short

Which set of headers are you in on each half? 

If you want both micros in the same orientation, then you need one to be in the outboard set, and the other in the inboard.  

Did you test before adding LEDs? 
Did you test with only a few LEDs? 

If you continue to refuse to try those two things, I suggest you remove the 5v and LED pins grow your micro, that should allow you to test the key matrix and confirm that it's an LED short.

**Comment by DLopezGo90** [comment]
I have both Pro Micro with the components facing the PCB and they are in the inboard set (with inboard you mean the holes inside the white silkscreen rectangles right?)

C'mon bro, I posted images. You can tell me by looking at them

I followed the guide, it says that both Pro Micro must have the components facing the PCB and that holes inside narrow white rectangles must be used to put the Pro Micro

![image](https://user-images.githubusercontent.com/59780264/120563521-c75b5000-c3d6-11eb-99f9-cba63db662e5.png)

Help please

**Comment by DLopezGo90** [comment]
![image](https://user-images.githubusercontent.com/59780264/120566683-bfeb7500-c3dd-11eb-846a-d3e3b5238812.png)

I have both Pro Micro with the components facing the PCB. I did it wrong?

**Comment by DaneEvans** [comment]
Ok. I'm done here.
You upload crappy images with  angles that don't even show the placements,
and want me to debug this for you from a timezone across the world.

While ignoring all of the questions that would lead us to a solution and
giving me attitude.

The only reason I have left it open this long is that I don't yet have
confirmation that anyone has a fully working build of this version of the
build.

Given that one of you has a working left board, and the other the right, I
think we can rule out a PCB issue, which means you're on your own.

**Comment by DLopezGo90** [comment]
I looked at danieltoro's images and it's clear that he used SK6812 Mini-E which has a different pin distribution and is probably the reason why he's having issues. I thought you were ignoring images because you didn't notice but if that's not the case I apologize

I used this version: https://github.com/josefadamcik/SofleKeyboard/blob/master/Sofle_RGB/PCB/SofleKeyboard.kicad_pcb 

![image](https://user-images.githubusercontent.com/59780264/120675832-6cbc0580-c463-11eb-8991-089a5251b5fd.png)

I can see it's the 2.0 version and it has that unconnected via for NET34 issue

![image](https://user-images.githubusercontent.com/59780264/120673740-704e8d00-c461-11eb-9dfb-d75f8a97d9e6.png)

So I had to do the bridges:

![image](https://user-images.githubusercontent.com/59780264/120674895-8e68bd00-c462-11eb-8f08-5893e547980d.png)

![image](https://user-images.githubusercontent.com/59780264/120675400-06cf7e00-c463-11eb-880c-7ef5578d4f9e.png)

In the beginning both halves were working but suddenly left half turned off and didn't work anymore

![image](https://user-images.githubusercontent.com/59780264/120676849-742fde80-c464-11eb-984b-167a79fc0a1e.png)

I don't  think it's a PCB issue because there's a guy in reddit who uses this Sofle RGB keyboard without problem
